#!/bin/bash

# Source tutorial run functions
source $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

if [ ! -f log.decomposePar ]; then
    ./Allrun.pre
fi

GMON_OUT_PREFIX=$application runParallel $application
# nProcs=$(foamDictionary system/decomposeParDict -entry numberOfSubdomains -value)
# mpirun -np $nProcs valgrind --tool=callgrind $application -parallel > log.$application 2>&1
runApplication reconstructPar -newTimes

./Allpost

#------------------------------------------------------------------------------
